{"level": "ERROR", "message": "exception message", "timestamp": "2024-09-21T16:00:06.292226+00:00", "logger": "myapp", "module": "main", "function": "main", "line": 26, "threadname": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"e:\\Python\\ImportantConcepts\\modern_logging\\main.py\", line 24, in main\n    1/0\n    ~^~\nZeroDivisionError: division by zero"}
